[package]
name = "rusty-machine"
version = "0.0.8"
authors = ["AtheMathmo"]

description = "An early stage machine learning library."
repository = "https://github.com/AtheMathmo/rusty-machine"
documentation = "https://AtheMathmo.github.io/rusty-machine/"
keywords = ["machine","learning","stats","statistics","algebra"]
readme = "../README.md"
license = "MIT"


[dependencies]
num = "0.1.28"
rand = "0.3.*"

